### ISSUE TITLE
Header changes

### ISSUE THREAD

**Issue by briri** [cdlib/dmptool-ui#3]
Please make the following changes to the header. Note that PR #1 starts some of these changes but they will likely need to be adjusted.

### General:

---

### When a user is not logged in (t-home or -generic templates):
- [ ] Remove the 'Home' link from the main nav. Users typically know they can click on the logo to get to the homepage
- [ ] Add a 'Sign in' link to the left of the 'Language' menu. This should only appear on the `t-generic` template
- [ ] Move the language menu (and new Sign in link) up so that it sits above (visually) the regular nav elements. I started this in PR #1 but you may need to adjust. It should be aligned with the top of the DMPTool logo

Example of home page changes:
<img width="688" alt="Screen Shot 2021-08-20 at 2 13 49 PM" src="https://user-images.githubusercontent.com/1204467/130293995-2bdc1933-89ea-4c11-88d9-11874f474ce9.png">

---

### When a user logs in (new template):
- [ ] Add a new template for when a user is logged in
- [ ] Add the Profile Menu next to the Language menu (see component in PR #1)
- [ ] Add a 'Dashboard' link to the main nav (in the same position the 'Home' link used to be). This should only be visible when the user is logged in

<img width="687" alt="Screen Shot 2021-08-20 at 2 14 53 PM" src="https://user-images.githubusercontent.com/1204467/130294150-a23f6706-4e77-473f-9164-60129915ba33.png">

---

- [ ] Add a sub-header row (only visible when user is logged in). It should contain 3 columns: the organization logo (if no logo is available it would display the name of the org (e.g. University of California, Merced), the link to the org's homepage and helpdesk email, and an Administration menu (see PR #1)
- [ ] Adjust these new columns so that the org logo is aligned with the DMPTool logo, the links are aligned with the 'Dahsboard' link in the main nav, and the 'Admin' menu is right-aligned with the language menu.
- [ ] Adjust the logo size so that the DMPTool logo is more prominent 

<img width="1281" alt="Screen Shot 2021-08-20 at 2 30 39 PM" src="https://user-images.githubusercontent.com/1204467/130295843-ac2ee641-83d1-43ce-9d35-c8d8894f953a.png">

---

### Tab ordering:
- [ ] Update the menu items so that they follow the tab order outlined in these screen shots. 

<img width="699" alt="Screen Shot 2021-08-20 at 2 11 57 PM" src="https://user-images.githubusercontent.com/1204467/130293834-8b58889b-02f7-42aa-9e5c-f12655f961c6.png">
